#
# Awesome App Landing Page Config
#

# Be sure all REQUIRED fields are filled out!

#
# General App Info
#
app:
  name: StudyIn # REQUIRED - Enter your app name
  android_id: com.ajou.StudyIn # Optional - Enter Android app id like: com.example.app

  icon: images/hi.png
  
  # Leave blank to auto-magically populate
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-icon-512.png
  # 512px or greater, square

  #favicon: # uncomment if uploading own favicon
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-favicon.png - can be .ico or .png
  # 16px or greater, square

  screenshot: images/final.jpg
  
  # Leave blank to auto-magically populate
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-screen-640x1136.png
  # 640x1136px

  #video: # uncomment if prefer to show a video preview in the screen instead of image
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-preview.mp4
  # 640x1136px

  #app_twitter: # uncomment if the app has a twitter account "@my-awesome-app"
  #creator_twitter: # uncomment if creator has a twitter account "@awesome-dev"
  #social_image: # uncomment and add an image - defaults to icon
  # This will show up when your url is shared on sites like facebook and twitter
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-social_image.png
  # 512px or greater, square or width = 2X height
#
# Marketing
#
marketing_header: Study with me everywhere, anytime # Optional
marketing_desc: 저희는 온라인 공부 학습환경을 개선해주는 Study-in입니다. 저희의 서비스를 이용하여 학습 일정을 계획적으로 설계해보고, 다양한 사람과 함께 공부할 수 있는 기회를 만들어보세요! 또한 커뮤니티 기능을 활용하여 스터디 메이트 구인이나 어려운 문제 질문도 시도해보세요! 구글플레이나 앱스토어에서 곧 다운로드 가능합니다.

#
# Social Links
#
# Includes an icon for each username you enter
#

social-links:
  github: /StudyIn-ajou
  facebook: /studyin07ajouuniv
  twitter:
  pinterest:
  instagram: /StudyIn/
  email: ajou.study.in@gmail.com
  youtube: # channel/<your_long_string> or <user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

#
# Enable/Disable Features & Page Elements
#
enable:
  app_icon: true
  smart_app_banner: true

#
# Device
#
# Available devices:
# * iphone-se-silver-vertical
# * iphone-se-space-gray-vertical
# * ipod-touch-blue-vertical
#
device: iphone-se-silver-vertical # REQUIRED

#
# Theme Settings
#
background_color: "#989898" # Optional
background_image: images/now.jpg # Optional - Use Relative path e.g. images/backgrounds/image.jpg
text_color: white # Optional
link_color: # Optional
social_link_color: white # Optional
download_button_background_color: "#0191FF" # Optional
download_button_text_color: white; # Optional

#
# Site Info
#
# If you want specific meta info for your <head></head> tags
#
title: StudyIn # Optional - Enter your site title
description: This site is StudyIn offcial website. # Optional - Enter your site description

#
# Google Analytics
#
google_analytics: # Enter your tracking code (e.g. UA-2110908-2) to activate tracking

#
# !! You don't need to change any of the configuration flags below !!
#

# The release of Awesome App Landing Page that you're using
version: v1.1.2

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
